/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintIndexRouteImport } from './routes/print/index'
import { Route as PrintBottleIndexRouteImport } from './routes/print/bottle/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintIndexRoute = PrintIndexRouteImport.update({
  id: '/print/',
  path: '/print/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBottleIndexRoute = PrintBottleIndexRouteImport.update({
  id: '/print/bottle/',
  path: '/print/bottle/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/print': typeof PrintIndexRoute
  '/print/bottle': typeof PrintBottleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/print': typeof PrintIndexRoute
  '/print/bottle': typeof PrintBottleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/print/': typeof PrintIndexRoute
  '/print/bottle/': typeof PrintBottleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/print' | '/print/bottle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/print' | '/print/bottle'
  id: '__root__' | '/' | '/print/' | '/print/bottle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrintIndexRoute: typeof PrintIndexRoute
  PrintBottleIndexRoute: typeof PrintBottleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/': {
      id: '/print/'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/bottle/': {
      id: '/print/bottle/'
      path: '/print/bottle'
      fullPath: '/print/bottle'
      preLoaderRoute: typeof PrintBottleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrintIndexRoute: PrintIndexRoute,
  PrintBottleIndexRoute: PrintBottleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
