/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintIndexRouteImport } from './routes/print/index'
import { Route as BottleOfTheDayIndexRouteImport } from './routes/bottle-of-the-day/index'
import { Route as PrintBottleNewIndexRouteImport } from './routes/print/bottle/new/index'
import { Route as PrintBottleExistingIndexRouteImport } from './routes/print/bottle/existing/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintIndexRoute = PrintIndexRouteImport.update({
  id: '/print/',
  path: '/print/',
  getParentRoute: () => rootRouteImport,
} as any)
const BottleOfTheDayIndexRoute = BottleOfTheDayIndexRouteImport.update({
  id: '/bottle-of-the-day/',
  path: '/bottle-of-the-day/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBottleNewIndexRoute = PrintBottleNewIndexRouteImport.update({
  id: '/print/bottle/new/',
  path: '/print/bottle/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintBottleExistingIndexRoute =
  PrintBottleExistingIndexRouteImport.update({
    id: '/print/bottle/existing/',
    path: '/print/bottle/existing/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bottle-of-the-day': typeof BottleOfTheDayIndexRoute
  '/print': typeof PrintIndexRoute
  '/print/bottle/existing': typeof PrintBottleExistingIndexRoute
  '/print/bottle/new': typeof PrintBottleNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bottle-of-the-day': typeof BottleOfTheDayIndexRoute
  '/print': typeof PrintIndexRoute
  '/print/bottle/existing': typeof PrintBottleExistingIndexRoute
  '/print/bottle/new': typeof PrintBottleNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bottle-of-the-day/': typeof BottleOfTheDayIndexRoute
  '/print/': typeof PrintIndexRoute
  '/print/bottle/existing/': typeof PrintBottleExistingIndexRoute
  '/print/bottle/new/': typeof PrintBottleNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bottle-of-the-day'
    | '/print'
    | '/print/bottle/existing'
    | '/print/bottle/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bottle-of-the-day'
    | '/print'
    | '/print/bottle/existing'
    | '/print/bottle/new'
  id:
    | '__root__'
    | '/'
    | '/bottle-of-the-day/'
    | '/print/'
    | '/print/bottle/existing/'
    | '/print/bottle/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BottleOfTheDayIndexRoute: typeof BottleOfTheDayIndexRoute
  PrintIndexRoute: typeof PrintIndexRoute
  PrintBottleExistingIndexRoute: typeof PrintBottleExistingIndexRoute
  PrintBottleNewIndexRoute: typeof PrintBottleNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/': {
      id: '/print/'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bottle-of-the-day/': {
      id: '/bottle-of-the-day/'
      path: '/bottle-of-the-day'
      fullPath: '/bottle-of-the-day'
      preLoaderRoute: typeof BottleOfTheDayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/bottle/new/': {
      id: '/print/bottle/new/'
      path: '/print/bottle/new'
      fullPath: '/print/bottle/new'
      preLoaderRoute: typeof PrintBottleNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/bottle/existing/': {
      id: '/print/bottle/existing/'
      path: '/print/bottle/existing'
      fullPath: '/print/bottle/existing'
      preLoaderRoute: typeof PrintBottleExistingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BottleOfTheDayIndexRoute: BottleOfTheDayIndexRoute,
  PrintIndexRoute: PrintIndexRoute,
  PrintBottleExistingIndexRoute: PrintBottleExistingIndexRoute,
  PrintBottleNewIndexRoute: PrintBottleNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
